---
- name: Install Docker
  gather_facts: No
  become: true
  hosts: all
 
  tasks:
    - name: Install yum utils, device-mapper-persistent-data, lvm2
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest
 
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
 
    - name: Install Docker, Docker-Ce-Cli, Install Docker,containerd.io
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
 
    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes